/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExplorerEditor.java
 *
 * Created on 2011/01/04, 15:40:39
 */
package jp.atr.dni.bmi.desktop.explorereditor;

import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.windows.TopComponent;

/**
 *
 * @author Keiji Harada [*1]</br>[*1] ATR Intl. Conputational Neuroscience Labs, Decoding Group
 * @version 2011/04/22
 */
public class ExplorerEditor extends TopComponent implements ExplorerManager.Provider {

    private final ExplorerManager mgr = new ExplorerManager();

    /** Creates new form ExplorerEditor */
    public ExplorerEditor() {
        initComponents();
        mgr.setRootContext(new ExplorerNode());
        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));
        setDisplayName("Files");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BeanTreeView btv = new BeanTreeView();
        btv.setRootVisible(false);
        jScrollPane1 = btv;

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }
}
