/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExplorerEditor.java
 *
 * Created on 2011/01/04, 15:40:39
 */
package jp.atr.dni.bmi.desktop.explorereditor;

import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;

/**
 *
 * @author kharada
 */
public class ExplorerEditor extends TopComponent implements ExplorerManager.Provider {

    private final ExplorerManager mgr = new ExplorerManager();
    private final InstanceContent content = new InstanceContent();

    /** Creates new form ExplorerEditor */
    public ExplorerEditor() {
        initComponents();
//        GeneralFileInfo obj = new GeneralFileInfo("C:\\Users\\kharada\\99_temp\\20110105\\test001.txt", "testtest");
//        associateLookup(Lookups.singleton(obj));
//        jTextField1.setText("Comment : " + obj.getComment());
//        jTextField2.setText("FilePath : " + obj.getFilePath());
//        setDisplayName("ExplorerEditor : " + obj.getFileName());
//        associateLookup(new AbstractLookup(content));
//        mgr.setRootContext(new AbstractNode(new ExplorerChildren()));
        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));
//        mgr.setRootContext(new AbstractNode(new ExplorerChildren()));
//        setDisplayName("Explorer Editor");
        mgr.setRootContext(new ExplorerNode());
//        mgr.setRootContext(new AbstractNode(new ExplorerChildren()));
        //setDisplayName("Explorer");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new BeanTreeView();

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }
}
