/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Timeline.java
 *
 * Created on 2010/10/29, 14:46:17
 */
package jp.atr.dni.bmi.desktop.timeline;

import javax.swing.JPanel;
import org.openide.windows.TopComponent;

/**
 *
 * @author makoto
 */
public class Timeline extends JPanel {

   /** Creates new form Timeline */
   public Timeline() {
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();

      jLabel1.setText(org.openide.util.NbBundle.getMessage(Timeline.class, "Timeline.jLabel1.text")); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(119, 119, 119)
            .addComponent(jLabel1)
            .addContainerGap(199, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(74, 74, 74)
            .addComponent(jLabel1)
            .addContainerGap(210, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   // End of variables declaration//GEN-END:variables
}
